
services:
  db:
    image: postgres:latest
    container_name: postgres_db_dpss
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dpss_service_db
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      mynetwork:
        aliases:
          - db.mynetwork

  backend:
    build: .
    container_name: backend
    restart: always
    depends_on:
      - db
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/dpss_service_db"
    volumes:
      - external_packages:/external_packages
    networks:
      mynetwork:
        aliases:
          - backend.mynetwork

volumes:
  db_data:
  external_packages:

networks:
  mynetwork:
    external:
      name: myglobalnetwork
